### ISSUE TITLE
fresh install crash

### ISSUE THREAD

**Issue by dacom-dark-sun** [icebob/vue-express-mongo-boilerplate#108]
After launch 'npm start' i try to open localhost:3000 and fail.

> vue-express-mongo-boilerplate@0.9.0 start /Users/darksun/dacom-code/vue-express-mongo-boilerplate
> cross-env NODE_ENV=production node server/index.js

process.argv: /Users/darksun/.nvm/versions/node/v6.12.0/bin/node,/Users/darksun/dacom-code/vue-express-mongo-boilerplate/server/index.js
Application root path: /Users/darksun/dacom-code/vue-express-mongo-boilerplate
Load production config...
info: 
info: ---------------------[ Server starting at 2018-05-26 13:32:27.554 ]---------------------------
info: 
info: Application root path: /Users/darksun/dacom-code/vue-express-mongo-boilerplate
info: 
info: Connecting to Mongo mongodb://localhost/boilerplate...
info:  
info: Search passport strategies...
info:   Loading passport strategy file apikey.js...
info:   Loading passport strategy file facebook.js...
info:   Loading passport strategy file github.js...
info:   Loading passport strategy file google.js...
info:   Loading passport strategy file local.js...
info:   Loading passport strategy file twitter.js...
info:  
info: Search built-in services...
info:   Load mailer.js service...
info:  
info: Search applogic services...
info:   Load counter/service.js service...
info:   Load devices/service.js service...
info:   Load persons/service.js service...
info:   Load posts/service.js service...
info:   Load profile/service.js service...
info:   Load session/service.js service...
info:  
info: VEM APP v1.0.0 application started!
info: ----------------------------------------------
info: Environment:	production
info: IP:		0.0.0.0
info: Port:		3000
info: Database:		mongodb://localhost/boilerplate
info: Redis:		Disabled
info:  
info: CPU:		Arch: x64, Cores: 8
info: Memory:		[||||||||||||||||---] 2.91 GB free
info: OS:		darwin (Darwin)
info: ----------------------------------------------
info: Mongo DB connected.
info: 
info: Agenda started!
debug: Seeding done!
error: Error: `line` is not an integer
    at Parser.initBlock (/Users/darksun/dacom-code/vue-express-mongo-boilerplate/node_modules/pug-parser/index.js:156:36)
    at Parser.emptyBlock (/Users/darksun/dacom-code/vue-express-mongo-boilerplate/node_modules/pug-parser/index.js:168:17)
    at Parser.block (/Users/darksun/dacom-code/vue-express-mongo-boilerplate/node_modules/pug-parser/index.js:989:22)
    at Parser.parseBlock (/Users/darksun/dacom-code/vue-express-mongo-boilerplate/node_modules/pug-parser/index.js:793:52)
    at Parser.parseExpr (/Users/darksun/dacom-code/vue-express-mongo-boilerplate/node_modules/pug-parser/index.js:212:21)
    at Parser.parse (/Users/darksun/dacom-code/vue-express-mongo-boilerplate/node_modules/pug-parser/index.js:112:25)
    at parse (/Users/darksun/dacom-code/vue-express-mongo-boilerplate/node_modules/pug-parser/index.js:12:20)
    at Object.parse (/Users/darksun/dacom-code/vue-express-mongo-boilerplate/node_modules/pug/lib/index.js:125:22)
    at Function.loadString [as string] (/Users/darksun/dacom-code/vue-express-mongo-boilerplate/node_modules/pug-load/index.js:45:21)
    at compileBody (/Users/darksun/dacom-code/vue-express-mongo-boilerplate/node_modules/pug/lib/index.js:86:18)
    at Object.exports.compile (/Users/darksun/dacom-code/vue-express-mongo-boilerplate/node_modules/pug/lib/index.js:242:16)
    at handleTemplateCache (/Users/darksun/dacom-code/vue-express-mongo-boilerplate/node_modules/pug/lib/index.js:215:25)
    at Object.exports.renderFile (/Users/darksun/dacom-code/vue-express-mongo-boilerplate/node_modules/pug/lib/index.js:427:10)
    at Object.exports.renderFile (/Users/darksun/dacom-code/vue-express-mongo-boilerplate/node_modules/pug/lib/index.js:417:21)
    at View.exports.__express [as engine] (/Users/darksun/dacom-code/vue-express-mongo-boilerplate/node_modules/pug/lib/index.js:464:11)
    at View.render (/Users/darksun/dacom-code/vue-express-mongo-boilerplate/node_modules/express/lib/view.js:135:8)
    at tryRender (/Users/darksun/dacom-code/vue-express-mongo-boilerplate/node_modules/express/lib/application.js:640:10)
    at EventEmitter.render (/Users/darksun/dacom-code/vue-express-mongo-boilerplate/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/Users/darksun/dacom-code/vue-express-mongo-boilerplate/node_modules/express/lib/response.js:1008:7)
    at ServerResponse.res.render (/Users/darksun/dacom-code/vue-express-mongo-boilerplate/node_modules/express-flash/lib/express-flash.js:29:16)
    at /Users/darksun/dacom-code/vue-express-mongo-boilerplate/server/routes/index.js:16:8
    at Layer.handle [as handle_request] (/Users/darksun/dacom-code/vue-express-mongo-boilerplate/node_modules/express/lib/router/layer.js:95:5)

**Comment by sust4in** [comment]
update pug package from 2.0.0 to 2.0.3

https://github.com/pugjs/pug/issues/2979

**Comment by sblattj** [comment]
had the same issue, @sust4in fix worked for me as well

**Comment by pikock** [comment]
updated pug to 2.03 in package.json, npm install again and still have the issue.
Did you guys do something else? @sust4in @sblattj

**Comment by sust4in** [comment]
i did  `npm run build` after changing the pugjs version.
