### ISSUE TITLE
npm run dev error on fresh install

### ISSUE THREAD

**Issue by WebShapedBiz** [icebob/vue-express-mongo-boilerplate#115]
Hi.
I'm getting 16 blocks with this error on my fresh npm run dev:

`ERROR in ./~/vue-loader/lib/template-compiler?{"id":"data-v-304449b2"}!./~/vue-loader/lib/template-compiler/preprocessor.js?raw&engine=pug!./~/vue-loader/lib/selector.js?type=template&index=0!./client/app/core/App.vue
Module build failed: Error: `line` is not an integer
    at Parser.initBlock (/home/sinisap/Dev/vue-express-mongo-boilerplate/node_modules/pug-parser/index.js:156:36)
    at Parser.emptyBlock (/home/sinisap/Dev/vue-express-mongo-boilerplate/node_modules/pug-parser/index.js:168:17)
    at Parser.parseTag (/home/sinisap/Dev/vue-express-mongo-boilerplate/node_modules/pug-parser/index.js:1040:19)
    at Parser.parseExpr (/home/sinisap/Dev/vue-express-mongo-boilerplate/node_modules/pug-parser/index.js:208:21)
    at Parser.parse (/home/sinisap/Dev/vue-express-mongo-boilerplate/node_modules/pug-parser/index.js:112:25)
    at parse (/home/sinisap/Dev/vue-express-mongo-boilerplate/node_modules/pug-parser/index.js:12:20)
    at Object.parse (/home/sinisap/Dev/vue-express-mongo-boilerplate/node_modules/pug/lib/index.js:125:22)
    at Function.loadString [as string] (/home/sinisap/Dev/vue-express-mongo-boilerplate/node_modules/pug-load/index.js:45:21)
    at compileBody (/home/sinisap/Dev/vue-express-mongo-boilerplate/node_modules/pug/lib/index.js:86:18)
    at Object.exports.compile (/home/sinisap/Dev/vue-express-mongo-boilerplate/node_modules/pug/lib/index.js:242:16)
    at /home/sinisap/Dev/vue-express-mongo-boilerplate/node_modules/consolidate/lib/consolidate.js:836:58
    at /home/sinisap/Dev/vue-express-mongo-boilerplate/node_modules/consolidate/lib/consolidate.js:144:5
    at Promise._execute (/home/sinisap/Dev/vue-express-mongo-boilerplate/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/home/sinisap/Dev/vue-express-mongo-boilerplate/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/home/sinisap/Dev/vue-express-mongo-boilerplate/node_modules/bluebird/js/release/promise.js:79:10)
    at promisify (/home/sinisap/Dev/vue-express-mongo-boilerplate/node_modules/consolidate/lib/consolidate.js:137:10)
    at Function.exports.pug.render (/home/sinisap/Dev/vue-express-mongo-boilerplate/node_modules/consolidate/lib/consolidate.js:821:10)
    at Object.module.exports (/home/sinisap/Dev/vue-express-mongo-boilerplate/node_modules/vue-loader/lib/template-compiler/preprocessor.js:44:20)
 @ ./client/app/core/App.vue 10:2-265
 @ ./client/app/main.js
 @ multi webpack-hot-middleware/client ./client/app/main.js
`

Before those 16 error blocks there is a warning:
`WARNING in webpack: Using NoErrorsPlugin is deprecated.
Use NoEmitOnErrorsPlugin instead.
`

The only thing that I've changed is fixing `nodemon --debug` with `nodemon --inspect` as it was suggested on one of the closed issues.

Thanx for the help.

**Comment by jcbolor** [comment]
Upgraded to pug 2.0.1.

**Comment by ernestoherrera** [comment]
I am having the same issue as WebShapedBiz.
I changed the plugins section of webpack.dev.config.js to the following with no success:
plugins: [
		new webpack.HotModuleReplacementPlugin(),
		new webpack.NoEmitOnErrorsPlugin()
	]

**Comment by ernestoherrera** [comment]
OK. I follow the recommendations in [this link.](https://github.com/linnovate/mean/issues/1711)  I did not have patch.exe in my path (Windows) 
That worked for me.
I still have a compiler error from the Vue Loader: "Module build failed: Error: `line` is not an integer. from App.vue
