### ISSUE TITLE
Unexpected token in agenda

### ISSUE THREAD

**Issue by AllMarketing-Victor** [icebob/vue-express-mongo-boilerplate#120]
Need help )
`web_1    | /usr/src/app/node_modules/agenda/lib/job/run.js:15
web_1    |   return new Promise(async(resolve, reject) => {
web_1    |                           ^
web_1    | 
web_1    | SyntaxError: Unexpected token (
web_1    |     at createScript (vm.js:56:10)
web_1    |     at Object.runInThisContext (vm.js:97:10)
web_1    |     at Module._compile (module.js:542:28)
web_1    |     at Object.Module._extensions..js (module.js:579:10)
web_1    |     at Module.load (module.js:487:32)
web_1    |     at tryModuleLoad (module.js:446:12)
web_1    |     at Function.Module._load (module.js:438:3)
web_1    |     at Module.require (module.js:497:17)
web_1    |     at require (internal/module.js:20:19)
web_1    |     at Object.<anonymous> (/usr/src/app/node_modules/agenda/lib/job/index.js:65:21)
web_1    |     at Module._compile (module.js:570:32)
web_1    |     at Object.Module._extensions..js (module.js:579:10)
web_1    |     at Module.load (module.js:487:32)
web_1    |     at tryModuleLoad (module.js:446:12)
web_1    |     at Function.Module._load (module.js:438:3)
web_1    |     at Module.require (module.js:497:17)
web_1    | [nodemon] app crashed - waiting for file changes before starting...
`

**Comment by AllMarketing-Victor** [comment]
node -v v8.12.0
npm -v 6.4.1

**Comment by luke-hawk** [comment]
+1

**Comment by gruf23** [comment]
+1

**Comment by danaia** [comment]
+1
