### ISSUE TITLE
help npm 

### ISSUE THREAD

**Issue by dnetto42** [icebob/vue-express-mongo-boilerplate#126]
npm run dev
or
docker-compose up 

blocked at `[nodemon] app crashed - waiting for file changes before starting...`

error msg:
```
web_1_281faff876a4 | /usr/src/app/node_modules/agenda/lib/job/run.js:15
web_1_281faff876a4 |   return new Promise(async(resolve, reject) => {
web_1_281faff876a4 |                           ^
web_1_281faff876a4 |
web_1_281faff876a4 | SyntaxError: Unexpected token (
web_1_281faff876a4 |     at createScript (vm.js:56:10)
web_1_281faff876a4 |     at Object.runInThisContext (vm.js:97:10)
web_1_281faff876a4 |     at Module._compile (module.js:542:28)
web_1_281faff876a4 |     at Object.Module._extensions..js (module.js:579:10)
web_1_281faff876a4 |     at Module.load (module.js:487:32)
web_1_281faff876a4 |     at tryModuleLoad (module.js:446:12)
web_1_281faff876a4 |     at Function.Module._load (module.js:438:3)
web_1_281faff876a4 |     at Module.require (module.js:497:17)
web_1_281faff876a4 |     at require (internal/module.js:20:19)
web_1_281faff876a4 |     at Object.<anonymous> (/usr/src/app/node_modules/agenda/lib/job/index.js:65:21)
web_1_281faff876a4 |     at Module._compile (module.js:570:32)
web_1_281faff876a4 |     at Object.Module._extensions..js (module.js:579:10)
web_1_281faff876a4 |     at Module.load (module.js:487:32)
web_1_281faff876a4 |     at tryModuleLoad (module.js:446:12)
web_1_281faff876a4 |     at Function.Module._load (module.js:438:3)
web_1_281faff876a4 |     at Module.require (module.js:497:17)
web_1_281faff876a4 | [nodemon] app crashed - waiting for file changes before starting...
```

**Comment by kmacpher67** [comment]
I tried this to get it to work;
```
nvm install 8.12.0
nvm alias default 8.12.0
npm i -g npm@6.4.1
npm install 
npm run dev
```
