### ISSUE TITLE
running on c9.io

### ISSUE THREAD

**Issue by honkskillet** [icebob/vue-express-mongo-boilerplate#14]
Hello,
I was able to get this up and running on my Mac, but I can't get this to run on Cloud9.  After cloning I run 
```
    npm install
    npm run dev
```
and I get 

```
`info: Search passport strategies...
info:   Loading passport strategy file apikey.js...
info:   Loading passport strategy file facebook.js...
info:   Loading passport strategy file github.js...
info:   Loading passport strategy file google.js...
info:   Loading passport strategy file local.js...
info:   Loading passport strategy file twitter.js...
module.js:327
    throw err;
    ^

Error: Cannot find module 'caniuse-db/features-json/transforms2d.json'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/workspace/vue-express-mongo-boilerplate/node_modules/autoprefixer/data/prefixes.js:109:11)
    at Object.<anonymous> (/home/ubuntu/workspace/vue-express-mongo-boilerplate/node_modules/autoprefixer/data/prefixes.js:587:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/workspace/vue-express-mongo-boilerplate/node_modules/autoprefixer/lib/autoprefixer.js:82:15)
    at Object.<anonymous> (/home/ubuntu/workspace/vue-express-mongo-boilerplate/node_modules/autoprefixer/lib/autoprefixer.js:91:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/workspace/vue-express-mongo-boilerplate/webpack.dev.config.js:8:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at initWebpack (/home/ubuntu/workspace/vue-express-mongo-boilerplate/server/core/express.js:285:18)
    at module.exports (/home/ubuntu/workspace/vue-express-mongo-boilerplate/server/core/express.js:331:2)
    at Object.<anonymous> (/home/ubuntu/workspace/vue-express-mongo-boilerplate/server/index.js:18:38)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
[nodemon] app crashed - waiting for file changes before starting...
^C[nodemon] exiting`
```

**Comment by icebob** [comment]
It's weird, I try to reproduce.

Maybe try to install deps with yarn.

**Comment by icebob** [comment]
I tested, and there is no problem with repo. It started properly.

**Comment by honkskillet** [comment]
Huh. That's weird.  Are there some other steps I'm missing beside npm install and npm run dev?  I'll try again.

**Comment by icebob** [comment]
No. I did same steps. Plus set a mongoDB uri in config.js.
This is my test workspace: https://ide.c9.io/icebob/vem

**Comment by honkskillet** [comment]
Yeah.  It worked.  I think I did something screwy in my first workspace (I was playing around with a generator first).  When I made a new workspace, I noticed that there was an option to clone the workspace from github right off the bat.  And it worked fine.

It's even easy to spin up a mongo instance right in cloud 9.  https://community.c9.io/t/setting-up-mongodb/1717

**Comment by honkskillet** [comment]
PS  Great boilerplate.  Ever think of turning it into a yo generator?

**Comment by icebob** [comment]
@honkskillet Thanks, I didn't know there is Mongo support on c9. I will try it.

Sorry, but I don't plan to make yo generator, it'll be a big job. Instead I develop the boilerplate code.

**Comment by honkskillet** [comment]
No need to apologize.  It's great boilerplate.  Thank you.
