### ISSUE TITLE
Could not connect to MongoDB!

### ISSUE THREAD

**Issue by jiji262** [icebob/vue-express-mongo-boilerplate#2]
darwin (Darwin)
info: ----------------------------------------------
error: Could not connect to MongoDB!
error:  Error: connect ECONNREFUSED 127.0.0.1:27017
    at Object.exports._errnoException (util.js:953:11)
    at exports._exceptionWithHostPort (util.js:976:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)

/vue-express-mongo-boilerplate/node_modules/mongodb/lib/server.js:228
        process.nextTick(function() { throw err; })
                                      ^
Error: connect ECONNREFUSED 127.0.0.1:27017
    at Object.exports._errnoException (util.js:953:11)
    at exports._exceptionWithHostPort (util.js:976:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
[nodemon] app crashed - waiting for file changes before starting...
^C

**Comment by icebob** [comment]
Did you install MongoDB server locally?
