### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by jfmmm** [icebob/vue-express-mongo-boilerplate#23]
Got an error when subscribing with an existing email...

```javascript
TypeError: Cannot read property 'split' of undefined
    at C:\Users\username\Desktop\projects\factorio-blueprint\server\routes\account.js:151:20
    at C:\Users\username\Desktop\projects\factorio-blueprint\node_modules\mongoose\lib\model.js:3408:16
    at C:\Users\username\Desktop\projects\factorio-blueprint\node_modules\mongoose\lib\document.js:2022:17
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

I did a console log of the error and here the result :

```javascript
{ MongoError: E11000 duplicate key error collection: boilerplate-dev.users index: email_1 dup key: { : "myemail@gmail.com" }
    at Function.MongoError.create (C:\Users\username\Desktop\projects\factorio-blueprint\node_modules\mongoose\node_modules\mongodb-core\lib\error.js:31:11)
    at toError (C:\Users\username\Desktop\projects\factorio-blueprint\node_modules\mongoose\node_modules\mongodb\lib\utils.js:114:22)
    at C:\Users\username\Desktop\projects\factorio-blueprint\node_modules\mongoose\node_modules\mongodb\lib\collection.js:657:23
    at handleCallback (C:\Users\username\Desktop\projects\factorio-blueprint\node_modules\mongoose\node_modules\mongodb\lib\utils.js:95:56)
    at C:\Users\username\Desktop\projects\factorio-blueprint\node_modules\mongoose\node_modules\mongodb\lib\bulk\unordered.js:465:9
    at handleCallback (C:\Users\username\Desktop\projects\factorio-blueprint\node_modules\mongoose\node_modules\mongodb\lib\utils.js:95:56)
    at resultHandler (C:\Users\username\Desktop\projects\factorio-blueprint\node_modules\mongoose\node_modules\mongodb\lib\bulk\unordered.js:413:5)
    at C:\Users\username\Desktop\projects\factorio-blueprint\node_modules\mongoose\node_modules\mongodb-core\lib\connection\pool.js:455:18
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  name: 'MongoError',
  message: 'E11000 duplicate key error collection: boilerplate-dev.users index: email_1 dup key: { : "myemail@gmail.com" }',
  driver: true,
  code: 11000,
  index: 0,
  errmsg: 'E11000 duplicate key error collection: boilerplate-dev.users index: email_1 dup key: { : "myemail@gmail.com" }',
  getOperation: [Function],
  toJSON: [Function],
  toString: [Function] }
```

**Comment by jfmmm** [comment]
Doesn't seem to happen in your demo, maybe it's because I don't have a mailer transport configured yet.

**Comment by icebob** [comment]
What kind of version of MongoDB are you using?
Because the account.js:151 this:

```js
let field = err.message.split(".$")[1];
field = field.split(" dup key")[0];
```

So the err.message should contain '.$' string, but yours is not.

Your Mongo's error message:
```
'E11000 duplicate key error collection: boilerplate-dev.users index: email_1 dup key: { : "myemail@gmail.com" }',```

my message (on live demo):
```
'E11000 duplicate key error index: vemapp.users.$email_1  dup key: { : "xxxxx@gmail.com" }'
```

**Comment by jfmmm** [comment]
a fresh install of the last version (3.4.1) on windows 10.
the `Windows Server 2008 R2 64-bit and later, without SSL support x64` version.

**Comment by av8ta** [comment]
I have the same problem. Changed the above two lines to this:

```
let field;
if(err.message.includes(".$")) {
  field = err.message.split(".$")[1];
}
else if (err.message.includes("index: ")) {
  field = err.message.split("index: ")[1];
}
else {
  req.flash("error", { msg: req.t("UserSaveError") });
  done(err, user);
  return
}
```

Ugly, but it's working :)

**Comment by icebob** [comment]
Nice, could you create a PR with fix?

**Comment by icebob** [comment]
:+1:
