### ISSUE TITLE
fallbackLoader option has been deprecated - replace with "fallback"

### ISSUE THREAD

**Issue by sw-yx** [icebob/vue-express-mongo-boilerplate#55]
`ice-services` branch
when i do `npm run build` off a fresh install i am now getting these two issues:

```
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
```

this causes a bunch of scary red errors like:
```
ERROR in ./~/css-loader?{"modules":true}!./~/postcss-loader!./~/sass-loader/lib/loader.js!./client/scss/frontend.scss
Module not found: Error: Can't resolve '~images/frontend-background.jpg' in '/Users/swyx/Desktop/webdev/vemb/vue-express-mongo-boilerplate/client/scss'
 @ ./~/css-loader?{"modules":true}!./~/postcss-loader!./~/sass-loader/lib/loader.js!./client/scss/frontend.scss 7:386-428 7:1282-1324
 @ ./client/scss/frontend.scss
 @ ./client/frontend/main.js
 @ multi ./client/frontend/main.js

ERROR in ./client/scss/frontend.scss
Module build failed: ModuleNotFoundError: Module not found: Error: Can't resolve '~images/frontend-background.jpg' in '/Users/swyx/Desktop/webdev/vemb/vue-express-mongo-boilerplate/client/scss'
    at factoryCallback (/Users/swyx/Desktop/webdev/vemb/vue-express-mongo-boilerplate/node_modules/webpack/lib/Compilation.js:260:39)
    at factory (/Users/swyx/Desktop/webdev/vemb/vue-express-mongo-boilerplate/node_modules/webpack/lib/NormalModuleFactory.js:247:20)
    at resolver (/Users/swyx/Desktop/webdev/vemb/vue-express-mongo-boilerplate/node_modules/webpack/lib/NormalModuleFactory.js:65:21)
    at asyncLib.parallel (/Users/swyx/Desktop/webdev/vemb/vue-express-mongo-boilerplate/node_modules/webpack/lib/NormalModuleFactory.js:138:21)
    at /Users/swyx/Desktop/webdev/vemb/vue-express-mongo-boilerplate/node_modules/async/dist/async.js:3824:9
    at /Users/swyx/Desktop/webdev/vemb/vue-express-mongo-boilerplate/node_modules/async/dist/async.js:460:16
    at iteratorCallback (/Users/swyx/Desktop/webdev/vemb/vue-express-mongo-boilerplate/node_modules/async/dist/async.js:1032:13)
    at /Users/swyx/Desktop/webdev/vemb/vue-express-mongo-boilerplate/node_modules/async/dist/async.js:944:16
    at /Users/swyx/Desktop/webdev/vemb/vue-express-mongo-boilerplate/node_modules/async/dist/async.js:3821:13
    at apply (/Users/swyx/Desktop/webdev/vemb/vue-express-mongo-boilerplate/node_modules/async/dist/async.js:21:25)
    at /Users/swyx/Desktop/webdev/vemb/vue-express-mongo-boilerplate/node_modules/async/dist/async.js:56:12
    at resolvers.normal.resolve (/Users/swyx/Desktop/webdev/vemb/vue-express-mongo-boilerplate/node_modules/webpack/lib/NormalModuleFactory.js:130:23)
    at onResolved (/Users/swyx/Desktop/webdev/vemb/vue-express-mongo-boilerplate/node_modules/enhanced-resolve/lib/Resolver.js:70:11)
    at loggingCallbackWrapper (/Users/swyx/Desktop/webdev/vemb/vue-express-mongo-boilerplate/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/Users/swyx/Desktop/webdev/vemb/vue-express-mongo-boilerplate/node_modules/enhanced-resolve/lib/Resolver.js:138:10)
    at loggingCallbackWrapper (/Users/swyx/Desktop/webdev/vemb/vue-express-mongo-boilerplate/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (/Users/swyx/Desktop/webdev/vemb/vue-express-mongo-boilerplate/node_modules/tapable/lib/Tapable.js:181:46)
    at innerCallback (/Users/swyx/Desktop/webdev/vemb/vue-express-mongo-boilerplate/node_modules/enhanced-resolve/lib/Resolver.js:125:19)
    at loggingCallbackWrapper (/Users/swyx/Desktop/webdev/vemb/vue-express-mongo-boilerplate/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /Users/swyx/Desktop/webdev/vemb/vue-express-mongo-boilerplate/node_modules/tapable/lib/Tapable.js:283:15
    at /Users/swyx/Desktop/webdev/vemb/vue-express-mongo-boilerplate/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:38:4
    at loggingCallbackWrapper (/Users/swyx/Desktop/webdev/vemb/vue-express-mongo-boilerplate/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/Users/swyx/Desktop/webdev/vemb/vue-express-mongo-boilerplate/node_modules/enhanced-resolve/lib/Resolver.js:138:10)
    at loggingCallbackWrapper (/Users/swyx/Desktop/webdev/vemb/vue-express-mongo-boilerplate/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (/Users/swyx/Desktop/webdev/vemb/vue-express-mongo-boilerplate/node_modules/tapable/lib/Tapable.js:181:46)
    at innerCallback (/Users/swyx/Desktop/webdev/vemb/vue-express-mongo-boilerplate/node_modules/enhanced-resolve/lib/Resolver.js:125:19)
    at loggingCallbackWrapper (/Users/swyx/Desktop/webdev/vemb/vue-express-mongo-boilerplate/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /Users/swyx/Desktop/webdev/vemb/vue-express-mongo-boilerplate/node_modules/tapable/lib/Tapable.js:283:15
    at innerCallback (/Users/swyx/Desktop/webdev/vemb/vue-express-mongo-boilerplate/node_modules/enhanced-resolve/lib/Resolver.js:123:11)
    at loggingCallbackWrapper (/Users/swyx/Desktop/webdev/vemb/vue-express-mongo-boilerplate/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)

ERROR in /Users/swyx/Desktop/webdev/vemb/vue-express-mongo-boilerplate/node_modules/extract-text-webpack-plugin/loader.js??ref--7-0!/Users/swyx/Desktop/webdev/vemb/vue-express-mongo-boilerplate/node_modules/style-loader/index.js!/Users/swyx/Desktop/webdev/vemb/vue-express-mongo-boilerplate/node_modules/css-loader/index.js??ref--7-2!/Users/swyx/Desktop/webdev/vemb/vue-express-mongo-boilerplate/node_modules/postcss-loader/index.js!/Users/swyx/Desktop/webdev/vemb/vue-express-mongo-boilerplate/node_modules/sass-loader/lib/loader.js!/Users/swyx/Desktop/webdev/vemb/vue-express-mongo-boilerplate/client/scss/frontend.scss doesn't export content
```

the solution may be to switch "loader" to "use" but im not sure. still trying to investigate. i am not sure if this has to do with my other compile issue where I see 

```
ERROR in ./client/app/core/App.vue
Module build failed: Error: 

Vue packages version mismatch:

- vue@2.2.6
- vue-template-compiler@https://registry.npmjs.org/vue-template-compiler/-/vue-template-compiler-2.2.6.tgz

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.
```

which looks like a nonsensical error

**Comment by sw-yx** [comment]
based on this https://github.com/angular/angular-cli/issues/4778

I have found that replacing `background-image: url('~images/frontend-background.jpg'); ` with `background-image: url('../images/frontend-background.jpg');` eliminates this particular error.

**Comment by icebob** [comment]
I fixed it in https://github.com/icebob/vue-express-mongo-boilerplate/commit/70c4f7db9754ec255ec84eba0638e98d81b7aa44
The URL of images is correct. The problem was the css modules.

Please update your fork ([info](https://gist.github.com/CristinaSolana/1885435))
