### ISSUE TITLE
problem with fresh instalation

### ISSUE THREAD

**Issue by vaske** [icebob/vue-express-mongo-boilerplate#67]
Hi there,

I pulled code base npm install went well. 
When I tried to start npm run dev it failed with this error

```
> cross-env NODE_ENV=development nodemon --debug

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn nodemon ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:592:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

on npm run build 

```

ERROR in ./client/app/main.js
Module build failed: Error: Couldn't find preset "env" relative to directory "/Users/vaske/projects/el-mail"
    at /Users/vaske/projects/el-mail/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/vaske/projects/el-mail/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/vaske/projects/el-mail/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/vaske/projects/el-mail/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/vaske/projects/el-mail/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/vaske/projects/el-mail/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/vaske/projects/el-mail/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/vaske/projects/el-mail/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/vaske/projects/el-mail/node_modules/babel-loader/lib/index.js:48:20)
    at Object.module.exports (/Users/vaske/projects/el-mail/node_modules/babel-loader/lib/index.js:163:20)
 @ multi ./client/app/main.js

ERROR in ./client/frontend/main.js
Module build failed: Error: Couldn't find preset "env" relative to directory "/Users/vaske/projects/el-mail"
    at /Users/vaske/projects/el-mail/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/vaske/projects/el-mail/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/vaske/projects/el-mail/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/vaske/projects/el-mail/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/vaske/projects/el-mail/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/vaske/projects/el-mail/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/vaske/projects/el-mail/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/vaske/projects/el-mail/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/vaske/projects/el-mail/node_modules/babel-loader/lib/index.js:48:20)
    at Object.module.exports (/Users/vaske/projects/el-mail/node_modules/babel-loader/lib/index.js:163:20)
 @ multi ./client/frontend/main.js
```

npm start works fine and I see application.

Any ideas did I miss something ?

**Comment by johncade** [comment]
@vaske in your `package.json` file, under `scripts`, change the `dev` script to:
```
 "dev": "cross-env NODE_ENV=development nodemon --inspect",
```
It appears `nodemon --debug` needs to be updated to `nodemon --inspect`. I changed this and it worked for me.
